PORT ?= 8000
run: build
	@./bin/app
build:
	@~/go/bin/templ generate && \
 {{- if and (or .Tailwind .Default) (not .Minimalistic) }}
	 npx tailwindcss -i tailwind/css/app.css -o public/styles.css && \
 {{- end }}
		 go build -o bin/app .

{{- if and (or .Tailwind .Default) (not .Minimalistic) }}
css:
	@npx tailwindcss -i tailwind/css/app.css -o public/styles.css --watch

{{- end }}
templ:
	~/go/bin/templ generate --watch --proxy=http://localhost:$(PORT)

{{- if and (or .Javascript .Htmx .Default) (not .Minimalistic) }}
build-js:
 {{- if or (and .Htmx .Javascript) .Default }}
	@curl -sLo public/scripts/htmx.min.js https://cdn.jsdelivr.net/npm/htmx.org/dist/htmx.min.js && \
	curl -sLo public/scripts/alpine.js https://cdn.jsdelivr.net/npm/alpinejs/dist/cdn.min.js && \
	curl -sLo public/scripts/jquery.min.js https://cdn.jsdelivr.net/npm/jquery/dist/jquery.min.js
	{{- else if .Htmx }}
	@curl -sLo public/scripts/htmx.min.js https://cdn.jsdelivr.net/npm/htmx.org/dist/htmx.min.js
	{{- else }}
	@curl -sLo public/scripts/alpine.js https://cdn.jsdelivr.net/npm/alpinejs/dist/cdn.min.js && \
	curl -sLo public/scripts/jquery.min.js https://cdn.jsdelivr.net/npm/jquery/dist/jquery.min.js
 {{- end }}

{{- end }}
{{- if and (or .Tailwind .Default) (not .Minimalistic) }}
tailwind:
	@npm install -D tailwindcss

{{- end }}
{{- if and (or .Esbuild .Default) (not .Minimalistic) }}
bundle-all: build-js build-css
	@echo "Bundling complete!"
build-js:
	@npx esbuild public/modules/main.js --minify --outfile=public/scripts/bundle.min.js
build-css:
	@npx esbuild public/styles/main.css --minify --outfile=public/styles/bundle.min.css

{{- end }}
{{- if and (or ( and .Esbuild .Tailwind) .Default) (not .Minimalistic) }}
npm-pkg:
	@npm install -D tailwindcss esbuild

{{- end }}