run: build
	@./bin/app
build:
	@~/go/bin/templ generate && \
 {{- if and (or .Tailwind .Default) (not .Minimalistic) }}
	 ./tailwindcss -i tailwind/css/app.css -o public/styles.css && \
 {{- end }}
		 go build -o bin/app .

{{- if and (or .Tailwind .Default) (not .Minimalistic) }}
css:
	./tailwindcss -i tailwind/css/app.css -o public/styles.css --watch

{{- end }}
templ:
	~/go/bin/templ generate --watch --proxy=http://localhost:8000

{{- if and (or .Javascript .Htmx .Default) (not .Minimalistic) }}
build-js:
 {{- if or (and .Htmx .Javascript) .Default }}
	@curl -sLo public/scripts/htmx.min.js https://cdn.jsdelivr.net/npm/htmx.org/dist/htmx.min.js && \
	curl -sLo public/scripts/alpine.js https://cdn.jsdelivr.net/npm/alpinejs/dist/cdn.min.js && \
	curl -sLo public/scripts/jquery.min.js https://cdn.jsdelivr.net/npm/jquery/dist/jquery.min.js
	{{- else if .Htmx }}
	@curl -sLo public/scripts/htmx.min.js https://cdn.jsdelivr.net/npm/htmx.org/dist/htmx.min.js
	{{- else }}
	@curl -sLo public/scripts/alpine.js https://cdn.jsdelivr.net/npm/alpinejs/dist/cdn.min.js && \
	curl -sLo public/scripts/jquery.min.js https://cdn.jsdelivr.net/npm/jquery/dist/jquery.min.js
 {{- end }}

{{- end }}
{{- if and (or .Tailwind .Default) (not .Minimalistic) }}
tailwind:
	@curl -sLo tailwindcss https://github.com/tailwindlabs/tailwindcss/releases/latest/download/tailwindcss-linux-x64 && \
	chmod +x tailwindcss
{{- end }}